### ISSUE TITLE
Client Example

### ISSUE THREAD

**Issue by Miserlou** [loye/proxy.stream#4]
I'm interested in adding SOCK5 support to a streaming client, is this project suitable for that? 

Is there any chance you could please make a client example for the README?

**Comment by loye** [comment]
var Proxy = require('proxy.stream').Proxy;
var remoteStream = new Proxy({ type: 'socks5', host: 'remote.hostname', port: 1080 });
remoteStream.on('error', function(err){ console.log(err); });
// you can just pipe your stream to the above "remoteStream".
yourStream.pipe(remoteStream).pipe(yourStream);

**Comment by Miserlou** [comment]
I'm slightly confused by that, is remoteStream the connection to the _remote_ host, or the proxy? Is Proxy() assuming that port:1080 is going to `localhost`? 

Supposing that I want to connect to 'bing.com:80' using 'localhost:1080' as a  SOCKS5 proxy, for instance.

**Comment by loye** [comment]
I'm afraid this Proxy is not for your case. I think what you need is just a function for connecting remote server through a SOCKS5 proxy. Please refer to the function connectSocks5 in lib/connector.js.
You can remake it by replacing endpoint as 'bing.com:80' and proxy as 'localhost:1080'. It returns the socket that you want.
